replicaCount: 2

image:
  repository: rdg5/birdapi
  tag: arm64
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 4201
  nodePort: 30001

resources: {}
birdimageapiReleaseName: "birdimageapi"

