replicaCount: 2

image:
  repository: rdg5/birdapi
  tag: arm64
  pullPolicy: Always

service:
  type: NodePort
  port: 4201
  nodePort: 30001

resources: {}
birdimageapiReleaseName: "birdimageapi"

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

