apiVersion: v1
kind: Service
metadata:
  name: birdimageapi
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "4200"
spec:
  type: ClusterIP
  selector:
    app: birdimageapi
  ports:
    - port: 4200
      targetPort: 4200
