apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-birdimageapi-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: birdimageapi
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
