apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-birdimageapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app: birdimageapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
