replicaCount: 2

image:
  repository: rdg5/birdimageapi
  tag: amd64
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4200

resources: {}

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
