---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add stable Helm repo
      shell: helm repo add stable https://charts.helm.sh/stable

    - name: Update Helm repositories
      shell: helm repo update

    - name: Deploy bird API using Helm
      shell: helm install birdimageapi /home/ubuntu/devops-challenge/helm-charts/birdImage/ -f /home/ubuntu/devops-challenge/helm-charts/birdImage/values-amd64.yaml

    - name: Deploy birdImage API using Helm
      shell: helm install birdapi /home/ubuntu/devops-challenge/helm-charts/bird/ -f /home/ubuntu/devops-challenge/helm-charts/bird/values-amd64.yaml --set birdImageApiReleaseName=birdimageapi

