{
 "title": "BirdApi Dashboard",
 "time": { "from": "2024-09-09T08:14:12.602Z", "to": "2024-09-09T13:12:05.983Z" },
 "panels": [
  {
   "title": "BirdApi total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total_birdapi", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BirdImageApi total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total_birdimageapi",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Events total",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_sd_kubernetes_events_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}