apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-birdapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app: birdapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default "30001" }}