apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-birdapi
  labels:
    app: birdapi
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: birdapi
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default "30001" }}
    